apiVersion : v1
kind: Deployment
metadata:
  name: login-app-deployment
  labels:
    app: login-app
    env: dev
spec:
  replicas: 3
  selector:
    matchLables:
      app: login-app
      env: dev
  template:
    metadata: 
      name: login-app
      labels: 
        app : login-app
        env: dev
    spec:
      containers:
        - name: login-app
          image: falcon646/myloginapp:v3
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            peroidSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            peroidSeconds: 10