apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-svc
  labels:
    app: nginx-frontend
    env: dev
spec:
  selector:
    app: nginx-frontend
    env: dev
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000