apiVersion: v1
kind: Pod
metadata:
  name: login-app
  labels:
    app: login
    env: dev
    createdby: ax025u
spec:
  containers:
    - name: login-app
      image: falcon646/myloginapp:v1
      ports:
        - containerPort: 8080