apiVersion: v1
kind: Service
metadata:
  name: login-app-svc
  labels:
    app: login
    env: dev
spec:
  selector:
    app: login
    env: dev
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
