apiVersion: v1
kind: Pod
metadata:
  name: nginx-frontend
  labels:
    app: nginx-frontend
    env: dev
spec:
  containers:
    - name: nginx-frontend
      image: falcon646/nginx-reverseproxy:v3
      ports:
      - containerPort: 80